# Generated by Django 5.1.3 on 2025-08-31 20:42

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='user_id',
            field=models.CharField(default=users.models.generate_unique_user_id, editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='appuser',
            table='registered_users',
        ),
    ]
